name: Deploy Pages

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - name: Use Pandoc 3.0.1
        uses: nikeee/setup-pandoc@v1
        with:
          pandoc-version: "3.0.1"
      - name: Use Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Clean
        run: npm run clean
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages